version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: elasticsearch
    environment:
      http.host: '0.0.0.0'
      network.host: '127.0.0.1'
      ES_JAVA_OPTS: '-Xms2g -Xmx2g -XX:-AssumeMP'
      bootstrap.memory_lock: 'true'
      reindex.remote.whitelist: "elasticsearch.higee.co:80"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 4096
        hard: 4096
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.4
    container_name: logstash
    environment:
        JAVA_OPTS: '-Xms512m -Xmx512m -XX:-AssumeMP'
    depends_on: ['elasticsearch']
    volumes:
      - ../driver:/usr/share/logstash/driver
      - ../data:/usr/share/logstash/data
      - ../../Week5_Logstash/code:/usr/share/logstash/code
    tty: true
    entrypoint: ["/bin/bash"]
    restart: always
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    depends_on: ['elasticsearch']
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    restart: always
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
     
