version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    container_name: elasticsearch
    environment:
      http.host: '0.0.0.0'
      network.host: '127.0.0.1'
      ES_JAVA_OPTS: '-Xms128m -Xmx128m'
      bootstrap.memory_lock: 'true'
      xpack.security.enabled: 'false'
      xpack.ml.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.4
    container_name: logstash
    environment:
      JAVA_OPTS: '-Xms128m -Xmx128m'
    depends_on: ['elasticsearch']
    networks:
      - elastic
    volumes:
      - ../../driver:/usr/share/logstash/driver
    tty: true
    restart: always
    entrypoint: ["/bin/bash"]

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - xpack.security.enabled=false
      - xpack.graph.enabled=false
      - xpack.reporting.enabled=false
    depends_on: ['elasticsearch']
    ports:
      - "5601:5601"
    restart: always
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
